services:
  - type: web
    name: real-estate-project
    env: php
    region: singapore
    plan: free
    branch: main

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
      chmod -R 775 storage bootstrap/cache

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ecommarce-cpii.onrender.com
      - key: APP_KEY
        value: base64:wJdU17eqFfInZTuEUqGYkQsS2ZG5L/QJE5tsBP2g66E=

      # Database - Replace with Render PostgreSQL info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d431k3hr0fns73f31mv0-a
      - key: DB_PORT
        value: 5432
      - key: ecommerce_db_xv5y
        value: <DB_DATABASE>
      - key: DB_USERNAME
        value: user123
      - key: DB_PASSWORD
        value: pjv1o7VqkJoWCGmHcv4rErqTNtA3BExH
