services:
  - type: web
    name: real-estate-project
    env: php
    region: singapore
    plan: free
    branch: main

    # Commands to run during build
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
      chmod -R 775 storage bootstrap/cache

    # Command to start Laravel on Render’s assigned port
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      # Laravel environment
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ecommarce-cpii.onrender.com
      - key: APP_KEY
        value: base64:wJdU17eqFfInZTuEUqGYkQsS2ZG5L/QJE5tsBP2g66E=

      # Database settings (replace with your actual Render DB info)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-xxxxxx.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ecommerce_db
      - key: DB_USERNAME
        value: user123
      - key: DB_PASSWORD
        value: password123
