services:
  - type: web
    name: real-estate-project
    env: php
    region: singapore
    plan: free
    branch: main

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
      chmod -R 775 storage bootstrap/cache

    startCommand: php artisan serve --host 0.0.0.0 --port 10000

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ecommarce-cpii.onrender.com
      # ⚠️ You must replace this APP_KEY below with your real one:
      - key: APP_KEY
        value: base64:wJdU17eqFfInZTuEUqGYkQsS2ZG5L/QJE5tsBP2g66E=

      # Optional: only if you use a database
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_DATABASE
        value: ecommerce.com
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value:
